# Generated by Django 5.2 on 2026-07-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tasklist_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['-id']},
        ),
    ]
